title: Package Propose
subtitle: '<{ Where libraries ask for your hand in development }/>'
email: barungisteven@gmail.com
author: Steve Baros
description: |
  The cloud solution  to find the right package/library for any project
disclaimer: >
  None of the packages recommended here have been fully evaluated to be free of
  malicious code,erronoues code and or malware .
baseurl: ''
url: 'https://packagepropose.com'
date_format: '%b %-d, %Y'
logo: /images/site/logo.png
header_pages:
  - about.md
  - contact.html
google_verification: null
google_analytics: UA-263637657
google_tag_manager: GTM-TBGSSLN
bing_verification: null
azure_appinsights_key: null
show_categories: true
animated: true
show_related_posts: true
show_post_footers: true
show_social_icons: true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: true
enable_anchorjs: false
post_preview_image: true
fb_page: false
fb_page_id: null
disqus_shortname: null
facebook_comments: null
facebook_appid: null
facebook_comments_number: 10
github_username: stevebaros
reddit_username: stevebaros
twitter_username: stevebaros
skype_username: null
linkedin_username: stevebaros
medium_id: stevebaros
defaults:
  - scope:
      path: ''
  - values:
      image: /images/site/logo.png
      author: Steve Baros
show_page_navigation: true
show_page_minutes: true
show_sharing_icons: true
share_email: true
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false
text:
  category:
    label: Category
    label-multi: Categories
  pagination:
    newer: Newer
    older: Older
  share_buttons:
    text: Share this post!
    facebook: Share on Facebook
    twitter: Share on Twitter
    googleplus: Share on Google+
    linkedin: Share on LinkedIn
    digg: Share on Digg
    tumblr: Share on Tumblr
    reddit: Share on Reddit
    stumbleupon: Share on StumbleUpon
    hackernews: Share on Hacker News
  post:
    updated: Updated
    minute_read: minute read
    related_posts: You might also like...
  index:
    coming_soon: Coming soon...
  contact:
    email: Email Address
    content: What would you like to say?
    subject: New submission!
    submit: Say Hello
    ajax:
      sending: sending..
      sent: Message sent!
      error: Error!
  thanks: Thanks for contacting us. We will reply as soon as possible.
  og_locale: en_US
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions:
    - smart
    - tables
    - with_toc_data
permalink: '/:title'
paginate: 7
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
gems:
  - jekyll-last-modified-at
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
theme: jekyll-theme-cayman
